name: Trigger deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main, master ]

jobs: 
  deploy_to_render:
      if: ${{ github.event_name == 'push' }}
      runs-on: ubuntu-22.04
      steps:
        - name: Trigger deployment
          run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
