name: Healthcheck

on:
  push:
    branches:
      - main

jobs:
  health_check:
    runs-on: ubuntu-22.04
    steps:
    - uses: jtalk/url-health-check-action@v4
      with:
        url: https://full-stack-open-pokedex-hnc0.onrender.com/
