name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    
jobs:
  simple_deployment_pipeline:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: p2pTest
        run: npm ci
              npx playwright install --with-deps
                npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
          
  tag_release:
    if: ${{ github.event_name == 'push' }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEFAULT_BUMP: patch
            NONE_STRING_TOKEN: "#skip"

  deploy_to_render:
      if: ${{ github.event_name == 'push' }}
      needs: [tag_release]
      runs-on: ubuntu-22.04
      steps:
        - name: Trigger deployment
          run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
        - name: Discord notification positive
          if: ${{ success() }}
          uses: sarisia/actions-status-discord@v1
          with:
            webhook: ${{ secrets.DISCORD_WEBHOOK }}
            description: "Deployment succeeded ✅"
            url: "https://github.com/eartto/full-stack-open-pokedex"
            username: GitHub Actions Bot

        - name: Discord notification negative
          if: ${{ failure() }}
          uses: sarisia/actions-status-discord@v1
          with:
            webhook: ${{ secrets.DISCORD_WEBHOOK }}
            description: "❌ Deployment failed"
            url: "https://github.com/eartto/full-stack-open-pokedex"
            username: GitHub Actions Bot
